name: string_util_xx
description: "String Util; number sort(1,2,11,22,111)、chinese pinyin sort/中文拼音排序"
version: 0.2.4
homepage: https://github.com/coolight7/string_util_xx

environment:
  sdk: ^2.19.6

dependencies:
  lpinyin:
    git:
      url: https://github.com/coolight7/lpinyin

dev_dependencies:
  test:
  lints: